# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ronin-asm}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Postmodern"]
  s.date = %q{2010-02-24}
  s.description = %q{Ronin ASM is a Ruby library for Ronin that provides dynamic Assembly (ASM) generation of programs or shellcode.}
  s.email = %q{postmodern.mod3@gmail.com}
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "README.md"
  ]
  s.files = [
    ".gitignore",
    ".specopts",
    ".yardopts",
    "COPYING.txt",
    "ChangeLog.md",
    "README.md",
    "Rakefile",
    "lib/ronin/asm.rb",
    "lib/ronin/asm/asm.rb",
    "lib/ronin/asm/version.rb",
    "lib/ronin/code/asm.rb",
    "lib/ronin/code/asm/code.rb",
    "lib/ronin/code/asm/config.rb",
    "ronin-asm.gemspec",
    "spec/asm_spec.rb",
    "spec/code/asm/code_spec.rb",
    "spec/code/asm/helpers/files.rb",
    "spec/code/asm/helpers/files/macros.s",
    "spec/code/asm/helpers/files/simple.s",
    "spec/helpers/database.rb",
    "spec/spec_helper.rb"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://github.com/ronin-ruby/ronin-asm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Ruby library for Ronin that provides dynamic Assembly (ASM) generation of programs or shellcode.}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/asm_spec.rb",
    "spec/helpers/database.rb",
    "spec/code/asm/code_spec.rb",
    "spec/code/asm/helpers/files.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi-udis86>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<ruby-yasm>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<ronin-ext>, [">= 0.1.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<yard>, [">= 0.5.3"])
    else
      s.add_dependency(%q<ffi-udis86>, [">= 0.1.0"])
      s.add_dependency(%q<ruby-yasm>, [">= 0.1.0"])
      s.add_dependency(%q<ronin-ext>, [">= 0.1.0"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<yard>, [">= 0.5.3"])
    end
  else
    s.add_dependency(%q<ffi-udis86>, [">= 0.1.0"])
    s.add_dependency(%q<ruby-yasm>, [">= 0.1.0"])
    s.add_dependency(%q<ronin-ext>, [">= 0.1.0"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<yard>, [">= 0.5.3"])
  end
end

